[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Tell netlify dev explicitly where your functions are for local development.
  functions = "netlify/functions"
  # NEW: Specify the command to start your client (React's dev server)
  command = "npm start --prefix client"
  # NEW: Specify the port your client's dev server runs on (default for Create React App)
  targetPort = 3000